// Code generated by wireinjectgen; DO NOT EDIT.
package wire

import (
	"github.com/google/wire"
	internal "html2pdf/internal"
	converter "html2pdf/internal/converter"
	middlewares "html2pdf/internal/middlewares"
)

var ProviderSet = wire.NewSet(
	internal.NewApp,
	internal.NewEcho,
	converter.NewPdfConverter,
	middlewares.NewRecoveryMiddleware,
	middlewares.NewResponseMiddleware,
)
