// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"html2pdf/internal"
	"html2pdf/internal/converter"
	"html2pdf/internal/middlewares"
)

// Injectors from wire.go:

func InitApp() *internal.App {
	echo := internal.NewEcho()
	responseMiddleware := middlewares.NewResponseMiddleware()
	recoveryMiddleware := middlewares.NewRecoveryMiddleware()
	pdfConverter := converter.NewPdfConverter()
	app := internal.NewApp(echo, responseMiddleware, recoveryMiddleware, pdfConverter)
	return app
}
